debug: false
bootstrap: []

logging_folder: '/Path/to/log/'

source_url:
  base_url: https://search-acc.uitdatabank.be/offers
  api_key: uuid
  parameters:
    q: 'labels:"owner-omd-2107"'
    embed: true
    availableFrom: '*'
    availableTo: '*'

destination:
  default_folder: 'OMD'
  local:
    active: true
    folder: '/path/to/folder'
  dropbox:
    active: false
    authorizationToken: 'T0k3n'
  ftp:
    active: false
    host: 'ftp://test.net'
    username: 'ftp_user'
    password: 'W@chtw00rd'
