debug: false
bootstrap: []

source_url:
  base_url: https://search-acc.uitdatabank.be/offers
  parameters:
    q: 'labels:"owner-omd-2107"'
    embed: true
    availableFrom: '*'
    availableTo: '*'
